---
roles:
  pe-puppet-master:
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    provider:
      type: virtualbox
      customize:
        - [modifyvm, !ruby/sym id, '--memory', 1024]
    provisioners:
      -
        type: hosts
      - type: shell
        inline: |-
          iptables -I INPUT 4 -p tcp --syn --dport 8140 -j ACCEPT
          iptables -I INPUT 4 -p tcp --syn --dport 61613 -j ACCEPT
      -
        type: pe_bootstrap
        role: !ruby/sym master

  pe-puppet-agent:
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    provisioners:
      - {type: hosts}
      - {type: pe_bootstrap}
