---
vms:
- name: master
  box: 'centos-64-x64-vbox4210-nocm'
  roles:
  - pe-puppet-master
- name: firstagent
  box: 'centos-64-x64-vbox4210-nocm'
  roles:
  - pe-puppet-agent
- name: secondagent
  box: 'debian-73-x64-virtualbox-nocm'
  roles:
  - pe-puppet-agent
